name: ♻️ Sync labels - Srealmoreno patched
on:
  workflow_dispatch:

  push:
    paths: [.github/labels.yml]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    name: ♻️ Sync labels
    runs-on: ubuntu-20.04
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      
      - name: 🚀 Run Label Sync
        uses: srealmoreno/label-sync@srealmoreno/bugfix/#142
        with:
          config-file: .github/labels.yml
