name: ♻️ Sync labels - Srealmoreno patched
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    name: ♻️ Sync labels
    runs-on: ubuntu-20.04
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      
      - name: 🚀 Run Label Sync
        uses: srealmoreno/label-sync@test/throw
        with:
          config-file: .github/labels.yml
